version: '3.9'

services:
  api:
    container_name: demo-api
    build:
      context: .
      target: dev
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - .:/app
    env_file:
      - .env
    working_dir: /app
    depends_on:
      - mongo
    command: pnpm dev

  mongo:
    image: mongo:latest
    container_name: demo-mongo
    ports:
      - '${MONGO_OPEN_PORT}:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
